In [1]:
import numpy as np
import pandas as pd


In [2]:
anime = pd.read_csv('datasets_anime/animes.csv')

In [60]:
temp = pd.read_csv('datasets_anime/animes.csv')

In [63]:
temp = temp.head(6000)

In [64]:
temp = temp.drop(columns=['title','img_url'])

In [38]:
anime = anime.head(6000)

In [39]:
anime.shape

(6000, 4)

In [5]:
#genres
#id
#synopsis
#title
#img_url
anime.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 19311 entries, 0 to 19310
Data columns (total 12 columns):
 #   Column      Non-Null Count  Dtype  
---  ------      --------------  -----  
 0   uid         19311 non-null  int64  
 1   title       19311 non-null  object 
 2   synopsis    18336 non-null  object 
 3   genre       19311 non-null  object 
 4   aired       19311 non-null  object 
 5   episodes    18605 non-null  float64
 6   members     19311 non-null  int64  
 7   popularity  19311 non-null  int64  
 8   ranked      16099 non-null  float64
 9   score       18732 non-null  float64
 10  img_url     19131 non-null  object 
 11  link        19311 non-null  object 
dtypes: float64(3), int64(3), object(6)
memory usage: 1.8+ MB


In [6]:
anime.isnull().sum()

uid              0
title            0
synopsis       975
genre            0
aired            0
episodes       706
members          0
popularity       0
ranked        3212
score          579
img_url        180
link             0
dtype: int64

In [7]:
anime = anime[['uid','title','genre','img_url']]

In [8]:
anime.dropna(inplace=True)

In [9]:
anime.duplicated().sum()

3080

In [10]:
anime.drop_duplicates(inplace=True)

In [11]:
anime.shape

(16051, 4)

In [66]:
temp.head(1)

uid                                           synopsis  \
0  28891  Following their participation at the Inter-Hig...   

                                               genre  \
0  ['Comedy', 'Sports', 'Drama', 'School', 'Shoun...   

                         aired  episodes  members  popularity  ranked  score  \
0  Oct 4, 2015 to Mar 27, 2016      25.0   489888         141    25.0   8.82   

                                                link  
0  https://myanimelist.net/anime/28891/Haikyuu_Se...

In [13]:
anime['genre'][0]

"['Comedy', 'Sports', 'Drama', 'School', 'Shounen']"

In [14]:
anime['genre'] = anime['genre'].apply(lambda x:x.lower())

In [15]:
anime['genre'] = anime['genre'].str.replace("'","")

In [16]:
anime['genre'].str.replace(" ","")

0                     [comedy,sports,drama,school,shounen]
1                     [drama,music,romance,school,shounen]
2                 [sci-fi,adventure,mystery,drama,fantasy]
3        [action,military,adventure,comedy,drama,magic,...
4                    [action,mystery,supernatural,vampire]
                               ...                        
19002       [action,comedy,superpower,martialarts,shounen]
19003                    [sliceoflife,comedy,supernatural]
19004                         [sliceoflife,comedy,shounen]
19005                                             [action]
19006            [comedy,drama,romance,school,sliceoflife]
Name: genre, Length: 16051, dtype: object

In [17]:
anime.head()

uid                             title  \
0  28891           Haikyuu!! Second Season   
1  23273           Shigatsu wa Kimi no Uso   
2  34599                     Made in Abyss   
3   5114  Fullmetal Alchemist: Brotherhood   
4  31758  Kizumonogatari III: Reiketsu-hen   

                                               genre  \
0           [comedy, sports, drama, school, shounen]   
1           [drama, music, romance, school, shounen]   
2       [sci-fi, adventure, mystery, drama, fantasy]   
3  [action, military, adventure, comedy, drama, m...   
4           [action, mystery, supernatural, vampire]   

                                             img_url  
0  https://cdn.myanimelist.net/images/anime/9/766...  
1  https://cdn.myanimelist.net/images/anime/3/671...  
2  https://cdn.myanimelist.net/images/anime/6/867...  
3  https://cdn.myanimelist.net/images/anime/1223/...  
4  https://cdn.myanimelist.net/images/anime/3/815...

In [40]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(max_features=5000,stop_words='english')

In [41]:
vectors = cv.fit_transform(anime['genre']).toarray()

In [42]:
vectors

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 1, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [1, 1, 0, ..., 0, 0, 0],
       [0, 0, 1, ..., 0, 0, 0]], dtype=int64)

In [43]:
vectors[0]

array([0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0,
       0, 0], dtype=int64)

In [44]:
cv.get_feature_names_out()

array(['action', 'adventure', 'ai', 'arts', 'cars', 'comedy', 'dementia',
       'demons', 'drama', 'ecchi', 'fantasy', 'fi', 'game', 'harem',
       'hentai', 'historical', 'horror', 'josei', 'kids', 'life', 'magic',
       'martial', 'mecha', 'military', 'music', 'mystery', 'parody',
       'police', 'power', 'psychological', 'romance', 'samurai', 'school',
       'sci', 'seinen', 'shoujo', 'shounen', 'slice', 'space', 'sports',
       'super', 'supernatural', 'thriller', 'vampire', 'yaoi', 'yuri'],
      dtype=object)

In [45]:
import nltk

In [46]:
from nltk.stem.porter import PorterStemmer
ps= PorterStemmer()

In [47]:
def stem(text):
    y=[]
    
    for i in text.split():
        y.append(ps.stem(i))
        
    return " ".join(y)

In [48]:
anime['genre'] = anime['genre'].apply(stem)

In [49]:
from sklearn.metrics.pairwise import cosine_similarity

In [50]:
similarity = cosine_similarity(vectors)

In [51]:
similarity[0]

array([1.        , 0.6       , 0.18257419, ..., 0.31622777, 0.14142136,
       0.2       ])

In [52]:
sorted(list(enumerate(similarity[0])),reverse=True,key=lambda x:x[1])[1:6]

[(10, 0.9999999999999999),
 (30, 0.9999999999999999),
 (86, 0.9999999999999999),
 (134, 0.9999999999999999),
 (163, 0.9999999999999999)]

In [53]:
def recommend(animes):
    anime_index = anime[anime['title'] == animes].index[0]
    distances = similarity[anime_index]
    anime_list = sorted(list(enumerate(distances)),reverse=True,key=lambda x:x[1])[1:6]
    
    for i in anime_list:
        print(anime.iloc[i[0]].title)

In [54]:
recommend('Naruto')

Naruto: Shippuuden
Dragon Ball Super Movie: Broly
Dragon Ball Z
Dragon Ball Kai
Dragon Ball Kai (2014)


In [55]:
import pickle

In [56]:
pickle.dump(anime,open('animes.pkl','wb'))

In [57]:
pickle.dump(anime.to_dict(),open('anime_dict.pkl','wb'))

In [58]:
pickle.dump(similarity,open('similarity.pkl','wb'))

In [59]:
anime['img_url']

0       https://cdn.myanimelist.net/images/anime/9/766...
1       https://cdn.myanimelist.net/images/anime/3/671...
2       https://cdn.myanimelist.net/images/anime/6/867...
3       https://cdn.myanimelist.net/images/anime/1223/...
4       https://cdn.myanimelist.net/images/anime/3/815...
                              ...                        
6427    https://cdn.myanimelist.net/images/anime/5/180...
6428    https://cdn.myanimelist.net/images/anime/1593/...
6429    https://cdn.myanimelist.net/images/anime/2/659...
6430    https://cdn.myanimelist.net/images/anime/12/85...
6431    https://cdn.myanimelist.net/images/anime/10/35...
Name: img_url, Length: 6000, dtype: object

In [65]:
pickle.dump(temp.to_dict(),open('temp_dict.pkl','wb'))